#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace asp.net实训_
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="safe")]
	public partial class safeDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void Insertcharge(charge instance);
    partial void Updatecharge(charge instance);
    partial void Deletecharge(charge instance);
    partial void Insertcomment(comment instance);
    partial void Updatecomment(comment instance);
    partial void Deletecomment(comment instance);
    partial void Insertcomplain(complain instance);
    partial void Updatecomplain(complain instance);
    partial void Deletecomplain(complain instance);
    partial void Insertparking(parking instance);
    partial void Updateparking(parking instance);
    partial void Deleteparking(parking instance);
    partial void InsertrepairAdmin(repairAdmin instance);
    partial void UpdaterepairAdmin(repairAdmin instance);
    partial void DeleterepairAdmin(repairAdmin instance);
    partial void Insertuser(user instance);
    partial void Updateuser(user instance);
    partial void Deleteuser(user instance);
    #endregion
		
		public safeDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["safeConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public safeDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public safeDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public safeDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public safeDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<charge> charge
		{
			get
			{
				return this.GetTable<charge>();
			}
		}
		
		public System.Data.Linq.Table<comment> comment
		{
			get
			{
				return this.GetTable<comment>();
			}
		}
		
		public System.Data.Linq.Table<complain> complain
		{
			get
			{
				return this.GetTable<complain>();
			}
		}
		
		public System.Data.Linq.Table<notice> notice
		{
			get
			{
				return this.GetTable<notice>();
			}
		}
		
		public System.Data.Linq.Table<parking> parking
		{
			get
			{
				return this.GetTable<parking>();
			}
		}
		
		public System.Data.Linq.Table<repairAdmin> repairAdmin
		{
			get
			{
				return this.GetTable<repairAdmin>();
			}
		}
		
		public System.Data.Linq.Table<user> user
		{
			get
			{
				return this.GetTable<user>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.charge")]
	public partial class charge : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _chargeId;
		
		private string _chargeType;
		
		private string _chargeDesc;
		
		private bool _isPay;
		
		private System.DateTime _chargeDate;
		
		private int _userId;
		
		private EntityRef<user> _user;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnchargeIdChanging(int value);
    partial void OnchargeIdChanged();
    partial void OnchargeTypeChanging(string value);
    partial void OnchargeTypeChanged();
    partial void OnchargeDescChanging(string value);
    partial void OnchargeDescChanged();
    partial void OnisPayChanging(bool value);
    partial void OnisPayChanged();
    partial void OnchargeDateChanging(System.DateTime value);
    partial void OnchargeDateChanged();
    partial void OnuserIdChanging(int value);
    partial void OnuserIdChanged();
    #endregion
		
		public charge()
		{
			this._user = default(EntityRef<user>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_chargeId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int chargeId
		{
			get
			{
				return this._chargeId;
			}
			set
			{
				if ((this._chargeId != value))
				{
					this.OnchargeIdChanging(value);
					this.SendPropertyChanging();
					this._chargeId = value;
					this.SendPropertyChanged("chargeId");
					this.OnchargeIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_chargeType", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string chargeType
		{
			get
			{
				return this._chargeType;
			}
			set
			{
				if ((this._chargeType != value))
				{
					this.OnchargeTypeChanging(value);
					this.SendPropertyChanging();
					this._chargeType = value;
					this.SendPropertyChanged("chargeType");
					this.OnchargeTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_chargeDesc", DbType="NVarChar(MAX)")]
		public string chargeDesc
		{
			get
			{
				return this._chargeDesc;
			}
			set
			{
				if ((this._chargeDesc != value))
				{
					this.OnchargeDescChanging(value);
					this.SendPropertyChanging();
					this._chargeDesc = value;
					this.SendPropertyChanged("chargeDesc");
					this.OnchargeDescChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isPay", DbType="Bit NOT NULL")]
		public bool isPay
		{
			get
			{
				return this._isPay;
			}
			set
			{
				if ((this._isPay != value))
				{
					this.OnisPayChanging(value);
					this.SendPropertyChanging();
					this._isPay = value;
					this.SendPropertyChanged("isPay");
					this.OnisPayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_chargeDate", DbType="DateTime NOT NULL")]
		public System.DateTime chargeDate
		{
			get
			{
				return this._chargeDate;
			}
			set
			{
				if ((this._chargeDate != value))
				{
					this.OnchargeDateChanging(value);
					this.SendPropertyChanging();
					this._chargeDate = value;
					this.SendPropertyChanged("chargeDate");
					this.OnchargeDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userId", DbType="Int NOT NULL")]
		public int userId
		{
			get
			{
				return this._userId;
			}
			set
			{
				if ((this._userId != value))
				{
					if (this._user.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnuserIdChanging(value);
					this.SendPropertyChanging();
					this._userId = value;
					this.SendPropertyChanged("userId");
					this.OnuserIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="user_charge", Storage="_user", ThisKey="userId", OtherKey="userId", IsForeignKey=true)]
		public user user
		{
			get
			{
				return this._user.Entity;
			}
			set
			{
				user previousValue = this._user.Entity;
				if (((previousValue != value) 
							|| (this._user.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._user.Entity = null;
						previousValue.charge.Remove(this);
					}
					this._user.Entity = value;
					if ((value != null))
					{
						value.charge.Add(this);
						this._userId = value.userId;
					}
					else
					{
						this._userId = default(int);
					}
					this.SendPropertyChanged("user");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.comment")]
	public partial class comment : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _commentId;
		
		private System.DateTime _commentDate;
		
		private string _commentContext;
		
		private string _commentUrl;
		
		private int _userId;
		
		private EntityRef<user> _user;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OncommentIdChanging(int value);
    partial void OncommentIdChanged();
    partial void OncommentDateChanging(System.DateTime value);
    partial void OncommentDateChanged();
    partial void OncommentContextChanging(string value);
    partial void OncommentContextChanged();
    partial void OncommentUrlChanging(string value);
    partial void OncommentUrlChanged();
    partial void OnuserIdChanging(int value);
    partial void OnuserIdChanged();
    #endregion
		
		public comment()
		{
			this._user = default(EntityRef<user>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_commentId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int commentId
		{
			get
			{
				return this._commentId;
			}
			set
			{
				if ((this._commentId != value))
				{
					this.OncommentIdChanging(value);
					this.SendPropertyChanging();
					this._commentId = value;
					this.SendPropertyChanged("commentId");
					this.OncommentIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_commentDate", DbType="DateTime NOT NULL")]
		public System.DateTime commentDate
		{
			get
			{
				return this._commentDate;
			}
			set
			{
				if ((this._commentDate != value))
				{
					this.OncommentDateChanging(value);
					this.SendPropertyChanging();
					this._commentDate = value;
					this.SendPropertyChanged("commentDate");
					this.OncommentDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_commentContext", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string commentContext
		{
			get
			{
				return this._commentContext;
			}
			set
			{
				if ((this._commentContext != value))
				{
					this.OncommentContextChanging(value);
					this.SendPropertyChanging();
					this._commentContext = value;
					this.SendPropertyChanged("commentContext");
					this.OncommentContextChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_commentUrl", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string commentUrl
		{
			get
			{
				return this._commentUrl;
			}
			set
			{
				if ((this._commentUrl != value))
				{
					this.OncommentUrlChanging(value);
					this.SendPropertyChanging();
					this._commentUrl = value;
					this.SendPropertyChanged("commentUrl");
					this.OncommentUrlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userId", DbType="Int NOT NULL")]
		public int userId
		{
			get
			{
				return this._userId;
			}
			set
			{
				if ((this._userId != value))
				{
					if (this._user.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnuserIdChanging(value);
					this.SendPropertyChanging();
					this._userId = value;
					this.SendPropertyChanged("userId");
					this.OnuserIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="user_comment", Storage="_user", ThisKey="userId", OtherKey="userId", IsForeignKey=true)]
		public user user
		{
			get
			{
				return this._user.Entity;
			}
			set
			{
				user previousValue = this._user.Entity;
				if (((previousValue != value) 
							|| (this._user.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._user.Entity = null;
						previousValue.comment.Remove(this);
					}
					this._user.Entity = value;
					if ((value != null))
					{
						value.comment.Add(this);
						this._userId = value.userId;
					}
					else
					{
						this._userId = default(int);
					}
					this.SendPropertyChanged("user");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.complain")]
	public partial class complain : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _complainId;
		
		private string _complainType;
		
		private string _complainDesc;
		
		private int _userId;
		
		private System.DateTime _complainDate;
		
		private EntityRef<user> _user;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OncomplainIdChanging(int value);
    partial void OncomplainIdChanged();
    partial void OncomplainTypeChanging(string value);
    partial void OncomplainTypeChanged();
    partial void OncomplainDescChanging(string value);
    partial void OncomplainDescChanged();
    partial void OnuserIdChanging(int value);
    partial void OnuserIdChanged();
    partial void OncomplainDateChanging(System.DateTime value);
    partial void OncomplainDateChanged();
    #endregion
		
		public complain()
		{
			this._user = default(EntityRef<user>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_complainId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int complainId
		{
			get
			{
				return this._complainId;
			}
			set
			{
				if ((this._complainId != value))
				{
					this.OncomplainIdChanging(value);
					this.SendPropertyChanging();
					this._complainId = value;
					this.SendPropertyChanged("complainId");
					this.OncomplainIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_complainType", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string complainType
		{
			get
			{
				return this._complainType;
			}
			set
			{
				if ((this._complainType != value))
				{
					this.OncomplainTypeChanging(value);
					this.SendPropertyChanging();
					this._complainType = value;
					this.SendPropertyChanged("complainType");
					this.OncomplainTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_complainDesc", DbType="NVarChar(MAX)")]
		public string complainDesc
		{
			get
			{
				return this._complainDesc;
			}
			set
			{
				if ((this._complainDesc != value))
				{
					this.OncomplainDescChanging(value);
					this.SendPropertyChanging();
					this._complainDesc = value;
					this.SendPropertyChanged("complainDesc");
					this.OncomplainDescChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userId", DbType="Int NOT NULL")]
		public int userId
		{
			get
			{
				return this._userId;
			}
			set
			{
				if ((this._userId != value))
				{
					if (this._user.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnuserIdChanging(value);
					this.SendPropertyChanging();
					this._userId = value;
					this.SendPropertyChanged("userId");
					this.OnuserIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_complainDate", DbType="DateTime NOT NULL")]
		public System.DateTime complainDate
		{
			get
			{
				return this._complainDate;
			}
			set
			{
				if ((this._complainDate != value))
				{
					this.OncomplainDateChanging(value);
					this.SendPropertyChanging();
					this._complainDate = value;
					this.SendPropertyChanged("complainDate");
					this.OncomplainDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="user_complain", Storage="_user", ThisKey="userId", OtherKey="userId", IsForeignKey=true)]
		public user user
		{
			get
			{
				return this._user.Entity;
			}
			set
			{
				user previousValue = this._user.Entity;
				if (((previousValue != value) 
							|| (this._user.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._user.Entity = null;
						previousValue.complain.Remove(this);
					}
					this._user.Entity = value;
					if ((value != null))
					{
						value.complain.Add(this);
						this._userId = value.userId;
					}
					else
					{
						this._userId = default(int);
					}
					this.SendPropertyChanged("user");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.notice")]
	public partial class notice
	{
		
		private int _noticeId;
		
		private string _noticeTitle;
		
		private string _noticeText;
		
		private System.DateTime _noticeDate;
		
		public notice()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_noticeId", DbType="Int NOT NULL")]
		public int noticeId
		{
			get
			{
				return this._noticeId;
			}
			set
			{
				if ((this._noticeId != value))
				{
					this._noticeId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_noticeTitle", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string noticeTitle
		{
			get
			{
				return this._noticeTitle;
			}
			set
			{
				if ((this._noticeTitle != value))
				{
					this._noticeTitle = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_noticeText", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string noticeText
		{
			get
			{
				return this._noticeText;
			}
			set
			{
				if ((this._noticeText != value))
				{
					this._noticeText = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_noticeDate", DbType="DateTime NOT NULL")]
		public System.DateTime noticeDate
		{
			get
			{
				return this._noticeDate;
			}
			set
			{
				if ((this._noticeDate != value))
				{
					this._noticeDate = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.parking")]
	public partial class parking : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _parkingId;
		
		private string _parkingBrand;
		
		private string _parkingType;
		
		private System.DateTime _parkingDate;
		
		private int _userId;
		
		private EntityRef<user> _user;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnparkingIdChanging(int value);
    partial void OnparkingIdChanged();
    partial void OnparkingBrandChanging(string value);
    partial void OnparkingBrandChanged();
    partial void OnparkingTypeChanging(string value);
    partial void OnparkingTypeChanged();
    partial void OnparkingDateChanging(System.DateTime value);
    partial void OnparkingDateChanged();
    partial void OnuserIdChanging(int value);
    partial void OnuserIdChanged();
    #endregion
		
		public parking()
		{
			this._user = default(EntityRef<user>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_parkingId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int parkingId
		{
			get
			{
				return this._parkingId;
			}
			set
			{
				if ((this._parkingId != value))
				{
					this.OnparkingIdChanging(value);
					this.SendPropertyChanging();
					this._parkingId = value;
					this.SendPropertyChanged("parkingId");
					this.OnparkingIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_parkingBrand", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string parkingBrand
		{
			get
			{
				return this._parkingBrand;
			}
			set
			{
				if ((this._parkingBrand != value))
				{
					this.OnparkingBrandChanging(value);
					this.SendPropertyChanging();
					this._parkingBrand = value;
					this.SendPropertyChanged("parkingBrand");
					this.OnparkingBrandChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_parkingType", DbType="NChar(10)")]
		public string parkingType
		{
			get
			{
				return this._parkingType;
			}
			set
			{
				if ((this._parkingType != value))
				{
					this.OnparkingTypeChanging(value);
					this.SendPropertyChanging();
					this._parkingType = value;
					this.SendPropertyChanged("parkingType");
					this.OnparkingTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_parkingDate", DbType="DateTime NOT NULL")]
		public System.DateTime parkingDate
		{
			get
			{
				return this._parkingDate;
			}
			set
			{
				if ((this._parkingDate != value))
				{
					this.OnparkingDateChanging(value);
					this.SendPropertyChanging();
					this._parkingDate = value;
					this.SendPropertyChanged("parkingDate");
					this.OnparkingDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userId", DbType="Int NOT NULL")]
		public int userId
		{
			get
			{
				return this._userId;
			}
			set
			{
				if ((this._userId != value))
				{
					if (this._user.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnuserIdChanging(value);
					this.SendPropertyChanging();
					this._userId = value;
					this.SendPropertyChanged("userId");
					this.OnuserIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="user_parking", Storage="_user", ThisKey="userId", OtherKey="userId", IsForeignKey=true)]
		public user user
		{
			get
			{
				return this._user.Entity;
			}
			set
			{
				user previousValue = this._user.Entity;
				if (((previousValue != value) 
							|| (this._user.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._user.Entity = null;
						previousValue.parking.Remove(this);
					}
					this._user.Entity = value;
					if ((value != null))
					{
						value.parking.Add(this);
						this._userId = value.userId;
					}
					else
					{
						this._userId = default(int);
					}
					this.SendPropertyChanged("user");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.repairAdmin")]
	public partial class repairAdmin : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _repairId;
		
		private int _userId;
		
		private string _repperName;
		
		private string _repairType;
		
		private System.DateTime _repairedDate;
		
		private System.DateTime _repairingDate;
		
		private string _repperPhone;
		
		private bool _isAccept;
		
		private bool _isSolve;
		
		private string _evaluateText;
		
		private EntityRef<user> _user;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnrepairIdChanging(int value);
    partial void OnrepairIdChanged();
    partial void OnuserIdChanging(int value);
    partial void OnuserIdChanged();
    partial void OnrepperNameChanging(string value);
    partial void OnrepperNameChanged();
    partial void OnrepairTypeChanging(string value);
    partial void OnrepairTypeChanged();
    partial void OnrepairedDateChanging(System.DateTime value);
    partial void OnrepairedDateChanged();
    partial void OnrepairingDateChanging(System.DateTime value);
    partial void OnrepairingDateChanged();
    partial void OnrepperPhoneChanging(string value);
    partial void OnrepperPhoneChanged();
    partial void OnisAcceptChanging(bool value);
    partial void OnisAcceptChanged();
    partial void OnisSolveChanging(bool value);
    partial void OnisSolveChanged();
    partial void OnevaluateTextChanging(string value);
    partial void OnevaluateTextChanged();
    #endregion
		
		public repairAdmin()
		{
			this._user = default(EntityRef<user>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_repairId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int repairId
		{
			get
			{
				return this._repairId;
			}
			set
			{
				if ((this._repairId != value))
				{
					this.OnrepairIdChanging(value);
					this.SendPropertyChanging();
					this._repairId = value;
					this.SendPropertyChanged("repairId");
					this.OnrepairIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userId", DbType="Int NOT NULL")]
		public int userId
		{
			get
			{
				return this._userId;
			}
			set
			{
				if ((this._userId != value))
				{
					if (this._user.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnuserIdChanging(value);
					this.SendPropertyChanging();
					this._userId = value;
					this.SendPropertyChanged("userId");
					this.OnuserIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_repperName", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string repperName
		{
			get
			{
				return this._repperName;
			}
			set
			{
				if ((this._repperName != value))
				{
					this.OnrepperNameChanging(value);
					this.SendPropertyChanging();
					this._repperName = value;
					this.SendPropertyChanged("repperName");
					this.OnrepperNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_repairType", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string repairType
		{
			get
			{
				return this._repairType;
			}
			set
			{
				if ((this._repairType != value))
				{
					this.OnrepairTypeChanging(value);
					this.SendPropertyChanging();
					this._repairType = value;
					this.SendPropertyChanged("repairType");
					this.OnrepairTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_repairedDate", DbType="DateTime NOT NULL")]
		public System.DateTime repairedDate
		{
			get
			{
				return this._repairedDate;
			}
			set
			{
				if ((this._repairedDate != value))
				{
					this.OnrepairedDateChanging(value);
					this.SendPropertyChanging();
					this._repairedDate = value;
					this.SendPropertyChanged("repairedDate");
					this.OnrepairedDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_repairingDate", DbType="DateTime NOT NULL")]
		public System.DateTime repairingDate
		{
			get
			{
				return this._repairingDate;
			}
			set
			{
				if ((this._repairingDate != value))
				{
					this.OnrepairingDateChanging(value);
					this.SendPropertyChanging();
					this._repairingDate = value;
					this.SendPropertyChanged("repairingDate");
					this.OnrepairingDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_repperPhone", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string repperPhone
		{
			get
			{
				return this._repperPhone;
			}
			set
			{
				if ((this._repperPhone != value))
				{
					this.OnrepperPhoneChanging(value);
					this.SendPropertyChanging();
					this._repperPhone = value;
					this.SendPropertyChanged("repperPhone");
					this.OnrepperPhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isAccept", DbType="Bit NOT NULL")]
		public bool isAccept
		{
			get
			{
				return this._isAccept;
			}
			set
			{
				if ((this._isAccept != value))
				{
					this.OnisAcceptChanging(value);
					this.SendPropertyChanging();
					this._isAccept = value;
					this.SendPropertyChanged("isAccept");
					this.OnisAcceptChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isSolve", DbType="Bit NOT NULL")]
		public bool isSolve
		{
			get
			{
				return this._isSolve;
			}
			set
			{
				if ((this._isSolve != value))
				{
					this.OnisSolveChanging(value);
					this.SendPropertyChanging();
					this._isSolve = value;
					this.SendPropertyChanged("isSolve");
					this.OnisSolveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_evaluateText", DbType="VarChar(MAX)")]
		public string evaluateText
		{
			get
			{
				return this._evaluateText;
			}
			set
			{
				if ((this._evaluateText != value))
				{
					this.OnevaluateTextChanging(value);
					this.SendPropertyChanging();
					this._evaluateText = value;
					this.SendPropertyChanged("evaluateText");
					this.OnevaluateTextChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="user_repairAdmin", Storage="_user", ThisKey="userId", OtherKey="userId", IsForeignKey=true)]
		public user user
		{
			get
			{
				return this._user.Entity;
			}
			set
			{
				user previousValue = this._user.Entity;
				if (((previousValue != value) 
							|| (this._user.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._user.Entity = null;
						previousValue.repairAdmin.Remove(this);
					}
					this._user.Entity = value;
					if ((value != null))
					{
						value.repairAdmin.Add(this);
						this._userId = value.userId;
					}
					else
					{
						this._userId = default(int);
					}
					this.SendPropertyChanged("user");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[user]")]
	public partial class user : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _userId;
		
		private string _userName;
		
		private string _userEmail;
		
		private string _userPhone;
		
		private string _userAddress;
		
		private string _userPassword;
		
		private EntitySet<charge> _charge;
		
		private EntitySet<comment> _comment;
		
		private EntitySet<complain> _complain;
		
		private EntitySet<parking> _parking;
		
		private EntitySet<repairAdmin> _repairAdmin;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnuserIdChanging(int value);
    partial void OnuserIdChanged();
    partial void OnuserNameChanging(string value);
    partial void OnuserNameChanged();
    partial void OnuserEmailChanging(string value);
    partial void OnuserEmailChanged();
    partial void OnuserPhoneChanging(string value);
    partial void OnuserPhoneChanged();
    partial void OnuserAddressChanging(string value);
    partial void OnuserAddressChanged();
    partial void OnuserPasswordChanging(string value);
    partial void OnuserPasswordChanged();
    #endregion
		
		public user()
		{
			this._charge = new EntitySet<charge>(new Action<charge>(this.attach_charge), new Action<charge>(this.detach_charge));
			this._comment = new EntitySet<comment>(new Action<comment>(this.attach_comment), new Action<comment>(this.detach_comment));
			this._complain = new EntitySet<complain>(new Action<complain>(this.attach_complain), new Action<complain>(this.detach_complain));
			this._parking = new EntitySet<parking>(new Action<parking>(this.attach_parking), new Action<parking>(this.detach_parking));
			this._repairAdmin = new EntitySet<repairAdmin>(new Action<repairAdmin>(this.attach_repairAdmin), new Action<repairAdmin>(this.detach_repairAdmin));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int userId
		{
			get
			{
				return this._userId;
			}
			set
			{
				if ((this._userId != value))
				{
					this.OnuserIdChanging(value);
					this.SendPropertyChanging();
					this._userId = value;
					this.SendPropertyChanged("userId");
					this.OnuserIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userName", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string userName
		{
			get
			{
				return this._userName;
			}
			set
			{
				if ((this._userName != value))
				{
					this.OnuserNameChanging(value);
					this.SendPropertyChanging();
					this._userName = value;
					this.SendPropertyChanged("userName");
					this.OnuserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userEmail", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string userEmail
		{
			get
			{
				return this._userEmail;
			}
			set
			{
				if ((this._userEmail != value))
				{
					this.OnuserEmailChanging(value);
					this.SendPropertyChanging();
					this._userEmail = value;
					this.SendPropertyChanged("userEmail");
					this.OnuserEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userPhone", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string userPhone
		{
			get
			{
				return this._userPhone;
			}
			set
			{
				if ((this._userPhone != value))
				{
					this.OnuserPhoneChanging(value);
					this.SendPropertyChanging();
					this._userPhone = value;
					this.SendPropertyChanged("userPhone");
					this.OnuserPhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userAddress", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string userAddress
		{
			get
			{
				return this._userAddress;
			}
			set
			{
				if ((this._userAddress != value))
				{
					this.OnuserAddressChanging(value);
					this.SendPropertyChanging();
					this._userAddress = value;
					this.SendPropertyChanged("userAddress");
					this.OnuserAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userPassword", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string userPassword
		{
			get
			{
				return this._userPassword;
			}
			set
			{
				if ((this._userPassword != value))
				{
					this.OnuserPasswordChanging(value);
					this.SendPropertyChanging();
					this._userPassword = value;
					this.SendPropertyChanged("userPassword");
					this.OnuserPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="user_charge", Storage="_charge", ThisKey="userId", OtherKey="userId")]
		public EntitySet<charge> charge
		{
			get
			{
				return this._charge;
			}
			set
			{
				this._charge.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="user_comment", Storage="_comment", ThisKey="userId", OtherKey="userId")]
		public EntitySet<comment> comment
		{
			get
			{
				return this._comment;
			}
			set
			{
				this._comment.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="user_complain", Storage="_complain", ThisKey="userId", OtherKey="userId")]
		public EntitySet<complain> complain
		{
			get
			{
				return this._complain;
			}
			set
			{
				this._complain.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="user_parking", Storage="_parking", ThisKey="userId", OtherKey="userId")]
		public EntitySet<parking> parking
		{
			get
			{
				return this._parking;
			}
			set
			{
				this._parking.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="user_repairAdmin", Storage="_repairAdmin", ThisKey="userId", OtherKey="userId")]
		public EntitySet<repairAdmin> repairAdmin
		{
			get
			{
				return this._repairAdmin;
			}
			set
			{
				this._repairAdmin.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_charge(charge entity)
		{
			this.SendPropertyChanging();
			entity.user = this;
		}
		
		private void detach_charge(charge entity)
		{
			this.SendPropertyChanging();
			entity.user = null;
		}
		
		private void attach_comment(comment entity)
		{
			this.SendPropertyChanging();
			entity.user = this;
		}
		
		private void detach_comment(comment entity)
		{
			this.SendPropertyChanging();
			entity.user = null;
		}
		
		private void attach_complain(complain entity)
		{
			this.SendPropertyChanging();
			entity.user = this;
		}
		
		private void detach_complain(complain entity)
		{
			this.SendPropertyChanging();
			entity.user = null;
		}
		
		private void attach_parking(parking entity)
		{
			this.SendPropertyChanging();
			entity.user = this;
		}
		
		private void detach_parking(parking entity)
		{
			this.SendPropertyChanging();
			entity.user = null;
		}
		
		private void attach_repairAdmin(repairAdmin entity)
		{
			this.SendPropertyChanging();
			entity.user = this;
		}
		
		private void detach_repairAdmin(repairAdmin entity)
		{
			this.SendPropertyChanging();
			entity.user = null;
		}
	}
}
#pragma warning restore 1591
